name: "Day-1-CI"

on:
  push:
    paths:
      - "Day-1/**"
      - ".github/workflows/day-1-ci.yml"

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        working-directory: Day-1/my-ci-cd-project
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest

      - name: Run tests
        working-directory: Day-1/my-ci-cd-project
        run: |
          python -m pytest tests/
