name: "Day-2-CI"

on:
  push:
    paths:
      - ".github/workflows/day-2-ci.yml"
      - "Day-2/**"

env:
  WAPP_NAME: JOD-WORKFLOW

jobs:
  lint:
    runs-on: ubuntu-latest
    env:
      JAPP_NAME: JOD-JOB
    steps:
      - name: "make directory enabled in ubuntu"
        uses: actions/checkout@v4

      - name: "Setup Python"
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: "Install dependencies"
        working-directory: Day-2/my-ci-cd-project
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: "Linting"
        working-directory: Day-2/my-ci-cd-project
        run: |
          python -m py_compile app/*.py

  tests:
    runs-on: ubuntu-latest

    steps:
      - name: "make directory enabled in ubuntu"
        uses: actions/checkout@v4

      - name: "Set up python"
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: "Install dependencies"
        working-directory: Day-2/my-ci-cd-project
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: "Testing"
        working-directory: Day-2/my-ci-cd-project
        run: |
          python -m pytest tests/

  build:
    needs: [tests, lint]
    runs-on: ubuntu-latest

    steps:
      - name: "make directory available in ubuntu"
        uses: actions/checkout@v4

      - name: "Envs printing :)"
        env:
          SAPP_NAME: JOD-STEP
        run: |
          echo "Application : $WAPP_NAME $JAPP_NAME $SAPP_NAME"

      - name: "build"
        working-directory: Day-2/my-ci-cd-project
        run: |
          mkdir -p build/
          cp -r app build/
          echo "build complete"
